// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RadioFrequencyIdentifier.proto

package DSCA.RadioFrequencyIdentifier;

public final class RadioFrequencyIdentifierImpl {
  private RadioFrequencyIdentifierImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Service3_scannerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Service3_scannerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Service3_scannerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Service3_scannerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Service3_tagRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Service3_tagRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Service3_tagResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Service3_tagResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036RadioFrequencyIdentifier.proto\022\010Servic" +
      "e3\"\"\n\016scannerRequest\022\020\n\010Scanner1\030\001 \001(\t\"#" +
      "\n\017scannerResponse\022\020\n\010scanner2\030\001 \001(\t\"\032\n\nt" +
      "agRequest\022\014\n\004tag1\030\001 \001(\t\"\033\n\013tagResponse\022\014" +
      "\n\004tag2\030\001 \001(\0052\224\001\n\030RadioFrequencyIdentifie" +
      "r\022B\n\007scanner\022\030.Service3.scannerRequest\032\031" +
      ".Service3.scannerResponse(\0010\001\0224\n\003tag\022\024.S" +
      "ervice3.tagRequest\032\025.Service3.tagRespons" +
      "e(\001B?\n\035DSCA.RadioFrequencyIdentifierB\034Ra" +
      "dioFrequencyIdentifierImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Service3_scannerRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Service3_scannerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Service3_scannerRequest_descriptor,
        new java.lang.String[] { "Scanner1", });
    internal_static_Service3_scannerResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Service3_scannerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Service3_scannerResponse_descriptor,
        new java.lang.String[] { "Scanner2", });
    internal_static_Service3_tagRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Service3_tagRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Service3_tagRequest_descriptor,
        new java.lang.String[] { "Tag1", });
    internal_static_Service3_tagResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Service3_tagResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Service3_tagResponse_descriptor,
        new java.lang.String[] { "Tag2", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
