// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RadioFrequencyIdentifier.proto

package DSCA.RadioFrequencyIdentifier;

public interface scannerResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Service3.scannerResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string scanner2 = 1;</code>
   */
  java.lang.String getScanner2();
  /**
   * <code>string scanner2 = 1;</code>
   */
  com.google.protobuf.ByteString
      getScanner2Bytes();
}
