// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RadioFrequencyIdentifier.proto

package DSCA.RadioFrequencyIdentifier;

public interface scannerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Service3.scannerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Scanner1 = 1;</code>
   */
  java.lang.String getScanner1();
  /**
   * <code>string Scanner1 = 1;</code>
   */
  com.google.protobuf.ByteString
      getScanner1Bytes();
}
