// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RadioFrequencyIdentifier.proto

package DSCA.RadioFrequencyIdentifier;

public interface tagResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Service3.tagResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 tag2 = 1;</code>
   */
  int getTag2();
}
