// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RadioFrequencyIdentifier.proto

package DSCA.RadioFrequencyIdentifier;

public interface tagRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Service3.tagRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tag1 = 1;</code>
   */
  java.lang.String getTag1();
  /**
   * <code>string tag1 = 1;</code>
   */
  com.google.protobuf.ByteString
      getTag1Bytes();
}
