// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RadioFrequencyIdentifier.proto

package DSCA.RadioFrequencyIdentifier;

/**
 * Protobuf type {@code Service3.tagRequest}
 */
public  final class tagRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Service3.tagRequest)
    tagRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use tagRequest.newBuilder() to construct.
  private tagRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private tagRequest() {
    tag1_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private tagRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            tag1_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return DSCA.RadioFrequencyIdentifier.RadioFrequencyIdentifierImpl.internal_static_Service3_tagRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return DSCA.RadioFrequencyIdentifier.RadioFrequencyIdentifierImpl.internal_static_Service3_tagRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            DSCA.RadioFrequencyIdentifier.tagRequest.class, DSCA.RadioFrequencyIdentifier.tagRequest.Builder.class);
  }

  public static final int TAG1_FIELD_NUMBER = 1;
  private volatile java.lang.Object tag1_;
  /**
   * <code>string tag1 = 1;</code>
   */
  public java.lang.String getTag1() {
    java.lang.Object ref = tag1_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tag1_ = s;
      return s;
    }
  }
  /**
   * <code>string tag1 = 1;</code>
   */
  public com.google.protobuf.ByteString
      getTag1Bytes() {
    java.lang.Object ref = tag1_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tag1_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTag1Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tag1_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTag1Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, tag1_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof DSCA.RadioFrequencyIdentifier.tagRequest)) {
      return super.equals(obj);
    }
    DSCA.RadioFrequencyIdentifier.tagRequest other = (DSCA.RadioFrequencyIdentifier.tagRequest) obj;

    boolean result = true;
    result = result && getTag1()
        .equals(other.getTag1());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TAG1_FIELD_NUMBER;
    hash = (53 * hash) + getTag1().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static DSCA.RadioFrequencyIdentifier.tagRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DSCA.RadioFrequencyIdentifier.tagRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DSCA.RadioFrequencyIdentifier.tagRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DSCA.RadioFrequencyIdentifier.tagRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DSCA.RadioFrequencyIdentifier.tagRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DSCA.RadioFrequencyIdentifier.tagRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DSCA.RadioFrequencyIdentifier.tagRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static DSCA.RadioFrequencyIdentifier.tagRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static DSCA.RadioFrequencyIdentifier.tagRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static DSCA.RadioFrequencyIdentifier.tagRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static DSCA.RadioFrequencyIdentifier.tagRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static DSCA.RadioFrequencyIdentifier.tagRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(DSCA.RadioFrequencyIdentifier.tagRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Service3.tagRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Service3.tagRequest)
      DSCA.RadioFrequencyIdentifier.tagRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DSCA.RadioFrequencyIdentifier.RadioFrequencyIdentifierImpl.internal_static_Service3_tagRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DSCA.RadioFrequencyIdentifier.RadioFrequencyIdentifierImpl.internal_static_Service3_tagRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DSCA.RadioFrequencyIdentifier.tagRequest.class, DSCA.RadioFrequencyIdentifier.tagRequest.Builder.class);
    }

    // Construct using DSCA.RadioFrequencyIdentifier.tagRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      tag1_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return DSCA.RadioFrequencyIdentifier.RadioFrequencyIdentifierImpl.internal_static_Service3_tagRequest_descriptor;
    }

    @java.lang.Override
    public DSCA.RadioFrequencyIdentifier.tagRequest getDefaultInstanceForType() {
      return DSCA.RadioFrequencyIdentifier.tagRequest.getDefaultInstance();
    }

    @java.lang.Override
    public DSCA.RadioFrequencyIdentifier.tagRequest build() {
      DSCA.RadioFrequencyIdentifier.tagRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public DSCA.RadioFrequencyIdentifier.tagRequest buildPartial() {
      DSCA.RadioFrequencyIdentifier.tagRequest result = new DSCA.RadioFrequencyIdentifier.tagRequest(this);
      result.tag1_ = tag1_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof DSCA.RadioFrequencyIdentifier.tagRequest) {
        return mergeFrom((DSCA.RadioFrequencyIdentifier.tagRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(DSCA.RadioFrequencyIdentifier.tagRequest other) {
      if (other == DSCA.RadioFrequencyIdentifier.tagRequest.getDefaultInstance()) return this;
      if (!other.getTag1().isEmpty()) {
        tag1_ = other.tag1_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      DSCA.RadioFrequencyIdentifier.tagRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (DSCA.RadioFrequencyIdentifier.tagRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object tag1_ = "";
    /**
     * <code>string tag1 = 1;</code>
     */
    public java.lang.String getTag1() {
      java.lang.Object ref = tag1_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tag1_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tag1 = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTag1Bytes() {
      java.lang.Object ref = tag1_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tag1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tag1 = 1;</code>
     */
    public Builder setTag1(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tag1_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string tag1 = 1;</code>
     */
    public Builder clearTag1() {
      
      tag1_ = getDefaultInstance().getTag1();
      onChanged();
      return this;
    }
    /**
     * <code>string tag1 = 1;</code>
     */
    public Builder setTag1Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      tag1_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Service3.tagRequest)
  }

  // @@protoc_insertion_point(class_scope:Service3.tagRequest)
  private static final DSCA.RadioFrequencyIdentifier.tagRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new DSCA.RadioFrequencyIdentifier.tagRequest();
  }

  public static DSCA.RadioFrequencyIdentifier.tagRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<tagRequest>
      PARSER = new com.google.protobuf.AbstractParser<tagRequest>() {
    @java.lang.Override
    public tagRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new tagRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<tagRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<tagRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public DSCA.RadioFrequencyIdentifier.tagRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

