// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Internet.proto

package DSCA.Internet;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Service1.Empty)
    com.google.protobuf.MessageOrBuilder {
}
