// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Internet.proto

package DSCA.Internet;

public final class InternetServiceImpl {
  private InternetServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Service1_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Service1_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Service1_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Service1_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Service1_SensorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Service1_SensorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Service1_SensorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Service1_SensorResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Internet.proto\022\010Service1\"F\n\007Message\022&\n" +
      "\006detail\030\001 \001(\0162\026.Service1.Message.Enum\"\023\n" +
      "\004Enum\022\013\n\007UNKNOWN\020\000\"\007\n\005Empty\"!\n\rSensorReq" +
      "uest\022\020\n\010inputVal\030\001 \001(\t\"#\n\016SensorResponse" +
      "\022\021\n\toutputVal\030\001 \001(\t2x\n\010Internet\022=\n\006Senso" +
      "r\022\027.Service1.SensorRequest\032\030.Service1.Se" +
      "nsorResponse\"\000\022-\n\005empty\022\021.Service1.Messa" +
      "ge\032\017.Service1.Empty\"\000B&\n\rDSCA.InternetB\023" +
      "InternetServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Service1_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Service1_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Service1_Message_descriptor,
        new java.lang.String[] { "Detail", });
    internal_static_Service1_Empty_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Service1_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Service1_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_Service1_SensorRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Service1_SensorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Service1_SensorRequest_descriptor,
        new java.lang.String[] { "InputVal", });
    internal_static_Service1_SensorResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Service1_SensorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Service1_SensorResponse_descriptor,
        new java.lang.String[] { "OutputVal", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
