// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Internet.proto

package DSCA.Internet;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Service1.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Service1.Message.Enum detail = 1;</code>
   */
  int getDetailValue();
  /**
   * <code>.Service1.Message.Enum detail = 1;</code>
   */
  DSCA.Internet.Message.Enum getDetail();
}
