// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Internet.proto

package DSCA.Internet;

public interface SensorRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Service1.SensorRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string inputVal = 1;</code>
   */
  java.lang.String getInputVal();
  /**
   * <code>string inputVal = 1;</code>
   */
  com.google.protobuf.ByteString
      getInputValBytes();
}
