// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Internet.proto

package DSCA.Internet;

public interface SensorResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Service1.SensorResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string outputVal = 1;</code>
   */
  java.lang.String getOutputVal();
  /**
   * <code>string outputVal = 1;</code>
   */
  com.google.protobuf.ByteString
      getOutputValBytes();
}
