// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Storage.proto

package DSCA.Storage;

public interface checkRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Service2.checkRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string check1 = 1;</code>
   */
  java.lang.String getCheck1();
  /**
   * <code>string check1 = 1;</code>
   */
  com.google.protobuf.ByteString
      getCheck1Bytes();
}
