// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Storage.proto

package DSCA.Storage;

public interface checkResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Service2.checkResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string check2 = 1;</code>
   */
  java.lang.String getCheck2();
  /**
   * <code>string check2 = 1;</code>
   */
  com.google.protobuf.ByteString
      getCheck2Bytes();
}
