// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Storage.proto

package DSCA.Storage;

public interface directRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Service2.directRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string direct1 = 1;</code>
   */
  java.lang.String getDirect1();
  /**
   * <code>string direct1 = 1;</code>
   */
  com.google.protobuf.ByteString
      getDirect1Bytes();
}
