// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Storage.proto

package DSCA.Storage;

public interface directResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Service2.directResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 direct2 = 1;</code>
   */
  int getDirect2();
}
