// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Storage.proto

package DSCA.Storage;

public final class StorageImpl {
  private StorageImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Service2_checkRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Service2_checkRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Service2_checkResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Service2_checkResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Service2_directRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Service2_directRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Service2_directResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Service2_directResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rStorage.proto\022\010Service2\"\036\n\014checkReques" +
      "t\022\016\n\006check1\030\001 \001(\t\"\037\n\rcheckResponse\022\016\n\006ch" +
      "eck2\030\001 \001(\t\" \n\rdirectRequest\022\017\n\007direct1\030\001" +
      " \001(\t\"!\n\016directResponse\022\017\n\007direct2\030\001 \001(\0052" +
      "\212\001\n\007Storage\022>\n\005check\022\026.Service2.checkReq" +
      "uest\032\027.Service2.checkResponse\"\000(\0010\001\022?\n\006d" +
      "irect\022\027.Service2.directRequest\032\030.Service" +
      "2.directResponse\"\000(\001B\035\n\014DSCA.StorageB\013St" +
      "orageImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Service2_checkRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Service2_checkRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Service2_checkRequest_descriptor,
        new java.lang.String[] { "Check1", });
    internal_static_Service2_checkResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Service2_checkResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Service2_checkResponse_descriptor,
        new java.lang.String[] { "Check2", });
    internal_static_Service2_directRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Service2_directRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Service2_directRequest_descriptor,
        new java.lang.String[] { "Direct1", });
    internal_static_Service2_directResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Service2_directResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Service2_directResponse_descriptor,
        new java.lang.String[] { "Direct2", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
